package com.minidmart.enums;

public enum AuditAction {
    USER_REGISTER,
    USER_LOGIN,
    USER_UPDATE,
    ROLE_CHANGE,
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
    STOCK_UPDATE,
    ORDER_CREATE,
    ORDER_STATUS_CHANGE,
    ORDER_CANCEL,
    RETURN_REQUEST,
    RETURN_APPROVE,
    RETURN_REJECT,
    RETURN_COMPLETE,
    EXCHANGE_REQUEST,
    EXCHANGE_APPROVE,
    EXCHANGE_REJECT,
    EXCHANGE_COMPLETE
}
